/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AES */

#ifndef _Included_AES
#define _Included_AES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AES
 * Method:    AESARM
 * Signature: ([BI)D
 */
JNIEXPORT jlong JNICALL Java_com_example_arm_AES_AESARM
  (JNIEnv *, jobject, jbyteArray, jint,jint);

/*
 * Class:     AES
 * Method:    AESNORMAL
 * Signature: ([BI)D
 */
JNIEXPORT jlong JNICALL Java_com_example_arm_AES_AESNORMAL
  (JNIEnv *, jobject, jbyteArray, jint,jint);

#ifdef __cplusplus
}
#endif
#endif
